sudo: required
services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
  - chmod 777 files
  - touch settings.php
  - chmod 777 settings.php
  - docker-compose up -d
  - docker exec -u user -w /var/www/web dbch_web drush si standard --db-url=mysql://drupal:drupal@db:3306/drupal
  - sleep 10
  - docker exec -u user -w /home/user/dev dbch_web composer install
  - docker exec -u user -w /home/user/dev dbch_web bin/behat -c tests/behat.yml tests/features/
